- name: Vulnerable DC
  hosts: dc
  gather_facts: true
  roles:
  - role: SetHostName
  - role: DeployAD
  - role: SetTimeZone
  - role: NukeDefender
  - role: EnableRemoteAccess
  - role: PasswordPolicy
  - role: AddDomainUsers
  - role: Impersonation
  - role: Kerberoast
  - role: Reboot

- name: Vulnerable Web
  hosts: web
  gather_facts: true
  become: true
  vars:
    app_dir: /opt/spanreed
  roles:
  - role: Passback