- name: Enable RDP
  ansible.windows.win_regedit:
    key: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    type: dword
    data: 0

- name: Allow remote desktop connections for all users
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: UserAuthentication
      data: 0
      type: dword

- name: Allow users to log on remotely
  ansible.windows.win_user_right:
    name: SeRemoteInteractiveLogonRight
    users: BUILTIN\Users
    action: add

- name: Allow Domain users to log on remotely
  ansible.windows.win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
      - Domain Users
    action: 
    
- name: Add Domain Users to Remote Desktop Users group
  ansible.windows.win_shell: net localgroup "Remote Desktop Users" "Domain Users" /add
  ignore_errors: true

- name: Add Domain Users to Remote Management group (Used for winrm)
  ansible.windows.win_shell: net localgroup "Remote Management Users" "Domain Users" /add
  ignore_errors: true
