- name: Set SPN for Adolin
  microsoft.ad.user:
    identity: "adolin"
    spn:
      set:
        - "mssql/adolin:1433"
  register: user_result
  until: user_result is not failed
  retries: 5
  delay: 15