- name: Register script to run on boot using Task Scheduler
  community.windows.win_scheduled_task:
    name: token
    description: "Do not delete"
    actions:
      - path: C:\Windows\System32\calc.exe
    triggers:
      - type: boot
        delay: P0Y0M0DT0H1M0S
        enabled: true
    run_level: highest
    logon_type: password
    state: present
    username: 'ROSHAR\adolin'
    password: "mayaiscool1"
    enabled: true
    author: ROSHAR\adolin
    compatability: 4
    multiple_instances: 2
    restart_count: 9
    restart_interval: P0Y0M0DT0H1M0S
    start_when_available: true
    allow_demand_start: true

- name: Giving Impersonation Privs to svc_spanreed!
  ansible.windows.win_user_right:
    name: "SeImpersonatePrivilege"
    users: 'ROSHAR\svc_spanreed'
    action: add