# Creates the Forest ROSHAR.LOCAL
- name: Create Forest
  microsoft.ad.domain:
    dns_domain_name: "ROSHAR.LOCAL"
    safe_mode_password: "P@$$w0rd!"
  register: domain_install

- name: Reboot if required
  ansible.windows.win_reboot:
  when: domain_install.reboot_required

- name: Ensure server is domain controller
  microsoft.ad.domain_controller:
    dns_domain_name: "ROSHAR.LOCAL"
    domain_admin_user: "Administrator@ROSHAR.LOCAL"
    domain_admin_password: "P@$$w0rd!"
    safe_mode_password: "P@$$w0rd!"
    state: domain_controller
    reboot: true
